kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-html-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Release.Name }}-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
