apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cd-token
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: cd
