apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-access-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-access-role
rules:
  # Правила для управления CRD otus.homework
  - apiGroups: ["otus.homework"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]

  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-access-binding
subjects:
  - kind: ServiceAccount
    name: mysql-access-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: mysql-access-role
  apiGroup: rbac.authorization.k8s.io
