apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html
    lifecycle:
      preStop:
        exec:
          command:
            - "rm"
            - "/usr/share/nginx/html/index.html"
  initContainers:
  - name: install
    image: busybox:stable
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://github.com
    volumeMounts:
    - name: html
      mountPath: "/init"
  volumes:
  - name: html
    emptyDir:
      sizeLimit: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: homework
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    name: nginx