apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-conf
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:1.3.0
        args: ["-nginx.scrape-uri=http://nginx:8000/status"]
        ports:
        - name: metrics
          containerPort: 9113
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: metrics
    port: 9113
    targetPort: metrics
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 8000;
      location /status {
        stub_status;
      }
    }
