name: "nginx"
namespace: "homework"
replicaCount: 3
maxUnavailable: 1
host: "homework.otus"
myUrl: "http://github.com"

image:
  repository: "nginx"
  tag: "1.27.0"

serviceAccount:
  name: "monitoring"

service:
  type: ClusterIP
  port: 8000
  
nginx:
  nginxConfigs:
    homework.conf: |
      server {
          listen 8000;
          root /homework;
          autoindex on;
      }
  customFiles:
    test: "123"
    foo: "bar"

readinessProbe:
  enabled: true
  httpGet:
    path: /index.html
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
