apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        homework: "true"
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
        lifecycle:
          preStop:
            exec:
              command:
                - "rm"
                - "/usr/share/nginx/html/index.html"
        readinessProbe:
          exec:
            command:
            - cat
            - /usr/share/nginx/html/index.html
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: install
        image: busybox:stable
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://github.com
        volumeMounts:
        - name: html
          mountPath: "/init"
      volumes:
      - name: html
        emptyDir:
          sizeLimit: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: nginx