kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-html-pvc
  namespace: homework  
spec:
  storageClassName: custom-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi